title: Fichier

sections:
  content:
    type: fields
    fields:
      caption:
        label: Légende & crédits
        type: markdown
        extends: fields/minimal
      alt:
        label: Alternative textuelle (description de l’image)
        type: text
