title: Default Page

columns :
  - width: 2/3
    sections:
      data:
        type: fields            
        fields:
          introduction:
            label: Introduction
            type: markdown
            extends: fields/md
            size: small
          text:
            label: Text
            type: markdown
            extends: fields/md
            size: medium
      pages:
        type: pages
        label: Pages
        layout: cardlets

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
                
          cover:
            label: Image  
            uploads:
              template: cover
            type: files
            max: 1
          metadescription:
            label: Description
            type: text
          metaimage:
            label: Image de partage 
            type: files
            max: 1
      files:
        type: files
        label: Fichiers  
