title: Site

columns: 
  - width: 2/3
    sections: 
      pages:
        type: pages
        status: all
        layout: cards
  - width: 1/3
    sections:
      data:
        type: fields
        fields:
          metadescription:
            label: Description
            type: text
          footer:
            label: Pied de page
            type: markdown
            extends: fields/md